In [5]:
test_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
length = len(test_list)
print(length)
avr = sum(test_list) / length

vari = []
for i in test_list:
    vari.append((i - avr) ** 2)

variance = sum(vari) / length
print(variance)

9
6.666666666666667


In [2]:
test_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
length = len(test_list)
avr = sum(test_list) / length

vari = []
for i in test_list:
    vari.append((i - avr) ** 2)

variance = sum(vari) / length
print("Variance:", variance)


Variance: 6.666666666666667


In [6]:
import numpy as np

test_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

variance = np.var(test_list)
print("Variance:", variance)


Variance: 6.666666666666667


In [8]:
import numpy as np   # 📦 ایمپورت کتابخانه NumPy

# 1️⃣ ساخت آرایه (Array)
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
# خروجی → [1 2 3 4 5]

# 2️⃣ عملیات ریاضی پایه روی کل آرایه
print("arr + 10 →", arr + 10)   # به همه‌ی عناصر ۱۰ اضافه می‌کنه → [11 12 13 14 15]
print("arr * 2  →", arr * 2)    # همه رو در ۲ ضرب می‌کنه → [ 2  4  6  8 10]
print("arr ** 2 →", arr ** 2)   # توان ۲ هر عنصر → [ 1  4  9 16 25]

# 3️⃣ آمار پایه
print("Mean:", np.mean(arr))                # میانگین → 3.0
print("Variance:", np.var(arr))             # واریانس جامعه → 2.0
print("Sample Variance:", np.var(arr, ddof=1))  # واریانس نمونه → 2.5
print("Standard Deviation:", np.std(arr))   # انحراف معیار → 1.4142135623730951
print("Sum:", np.sum(arr))                  # مجموع → 15
print("Product:", np.prod(arr))             # حاصل‌ضرب کل عناصر → 120
print("Min:", np.min(arr), "| Max:", np.max(arr))   # کمترین و بیشترین → 1 و 5
print("Index of Min:", np.argmin(arr), "| Index of Max:", np.argmax(arr))
# اندیس کوچک‌ترین (0) و بزرگ‌ترین (4)

# 4️⃣ تولید داده تصادفی
print("Random ints:", np.random.randint(1, 10, size=5))
# پنج عدد صحیح تصادفی بین 1 تا 9 (مثلاً [8 3 6 4 9])
print("Random floats (0–1):", np.random.rand(3))
# سه عدد اعشاری بین 0 و 1 (مثلاً [0.18 0.75 0.42])
print("Normal distribution:", np.random.randn(3))
# سه عدد از توزیع نرمال (مثلاً [0.23 -1.02 1.47])

# 5️⃣ تغییر شکل و ساخت داده
arr2 = np.arange(1, 7)   # تولید آرایه ۱ تا ۶ → [1 2 3 4 5 6]
print("Reshape (2x3):\n", arr2.reshape(2, 3))
# تغییر شکل به ماتریس ۲ سطری و ۳ ستونی →
# [[1 2 3]
#  [4 5 6]]
print("arange(0,10,2):", np.arange(0, 10, 2))
# تولید اعداد از ۰ تا ۸ با گام ۲ → [0 2 4 6 8]
print("linspace(0,1,5):", np.linspace(0, 1, 5))
# پنج عدد مساوی بین ۰ تا ۱ → [0.   0.25 0.5  0.75 1.  ]

# 6️⃣ مرتب‌سازی و حذف تکراری‌ها
arr3 = np.array([3, 1, 2, 3, 2, 1])
print("Sorted:", np.sort(arr3))     # مرتب‌سازی صعودی → [1 1 2 2 3 3]
print("Unique:", np.unique(arr3))   # حذف تکراری‌ها → [1 2 3]

# 7️⃣ ضرب ماتریسی
a = np.array([[1, 2], [3, 4]])   # ماتریس ۲×۲
b = np.array([[5, 6], [7, 8]])   # ماتریس ۲×۲ دیگر
print("Dot product:\n", np.dot(a, b))
# ضرب ماتریسی:
# [[(1*5 + 2*7)  (1*6 + 2*8)]
#  [(3*5 + 4*7)  (3*6 + 4*8)]]
# → [[19 22]
#    [43 50]]


Array: [1 2 3 4 5]
arr + 10 → [11 12 13 14 15]
arr * 2  → [ 2  4  6  8 10]
arr ** 2 → [ 1  4  9 16 25]
Mean: 3.0
Variance: 2.0
Sample Variance: 2.5
Standard Deviation: 1.4142135623730951
Sum: 15
Product: 120
Min: 1 | Max: 5
Index of Min: 0 | Index of Max: 4
Random ints: [9 3 7 3 1]
Random floats (0–1): [0.80618225 0.48615822 0.73526863]
Normal distribution: [-1.33677426 -0.4501508  -1.19673519]
Reshape (2x3):
 [[1 2 3]
 [4 5 6]]
arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
Sorted: [1 1 2 2 3 3]
Unique: [1 2 3]
Dot product:
 [[19 22]
 [43 50]]
